### PR TITLE
Changed some configuration checks to allow MinGW to build

### PR DESCRIPTION
**Pull request by cwsamuelson**
# Description

Change a couple CMake `if` guards to guard for MSVC, not windows as a whole.  Guarding WIN32 is overly scoped for MSVC specific flags, and prevents non-MSVC compilers to build on windows.

# Motivation

- Enables MinGW build
- More accurately expresses when certain flags should be used (i.e. flags apply to MSVC, not 'windows')

# Benefits

Enables builds with MinGW

# Drawbacks

None that I am aware of

# Applicable Issues

None

### CODE REVIEW

**Comment by SDX-LV** [comment]
Hi cwsamuelson, could you post a short how-to, which commands and which approach you use to compile PMP Library in Windows?

I have written for myself (so far don't know where to publish it) a step-by step tutorial to compile PMP Library on Windows using CMake and Visual Studio, but I would prefer a different compiler because https://github.com/cg-tub/hrtf_mesh_grading does not (yet) compile in Visual Studio.

**Comment by dsieger** [comment]
Thanks @cwsamuelson

**Comment by cwsamuelson** [comment]
> Hi cwsamuelson, could you post a short how-to, which commands and which approach you use to compile PMP Library in Windows?
> 
> I have written for myself (so far don't know where to publish it) a step-by step tutorial to compile PMP Library on Windows using CMake and Visual Studio, but I would prefer a different compiler because https://github.com/cg-tub/hrtf_mesh_grading does not (yet) compile in Visual Studio.

Hey, @SDX-LV , I haven't taken the time to look at github the last couple weeks, hopefully you can still find this reply.

My build environment is thus:
Windows10
Clion
MinGW

In order to build PMP, I added it as a submodule to my project at _vendor/pmp-library_, and in my main CMakeLists.txt, I added:
```
set(PMP_BUILD_APPS OFF CACHE BOOL "Build the PMP applications" FORCE)
set(PMP_BUILD_EXAMPLES OFF CACHE BOOL "Build the PMP examples" FORCE)
set(PMP_BUILD_TESTS OFF CACHE BOOL "Build the PMP test programs" FORCE)
set(PMP_BUILD_DOCS OFF CACHE BOOL "Build the PMP documentation" FORCE)
set(PMP_BUILD_VIS OFF CACHE BOOL "Build the PMP visualization tools" FORCE)
set(PMP_INSTALL ON CACHE BOOL "Install the PMP library and headers" FORCE)
ADD_SUBDIRECTORY(vendor/pmp-library)
```

The `set` commands disable the tests/examples/etc that I don't need to build it as a library for my project.

Then later on, I have a `TARGET_LINK_LIBRARIES(${PROJECT_NAME} pmp)`

This is sufficient for my project to build/link/use PMP.

If you need anything else, this PR thread probably isn't the best place for that discussion (I would think).

**Comment by SDX-LV** [comment]
Hi @cwsamuelson !  you have no idea how much your comment helped me. I ended up using MinGW32 to compile https://github.com/cg-tub/hrtf_mesh_grading . It was impossible with Visual Studio, but after some fighting it now works.
Massive difference compared to using Docker with Linux virtual environment.

**Pull request merged**
