### PR TITLE
Allow to use Eigen from system or from a custom installation

### PR DESCRIPTION
**Pull request by sloriot**
I put 3.1.0 but maybe an older version could be used.

### CODE REVIEW

**Comment by dsieger** [comment]
I was thinking about supporting custom third-party installations. However, I'm not sure I like it. After all, there are reasons why we are shipping our own copies, e.g., to avoid supporting and testing older library versions.

Furthermore, the current change would prefer versions found by the FindEigen3 script. The default should remain to use the bundled version.

Another concern is consistency: Offering this option only for Eigen and not for other third-party libraries is somewhat inconsistent.

**Comment by dsieger** [comment]
Closing due to reasons given above.

**Comment by dsieger** [comment]
FYI, I cherry-picked your change into our main branch and changed the default behavior to use our bundled version. I could not just re-open your PR since we migrated from master to main...

**Comment by sloriot** [comment]
Ah that's a good news! It means that I can probably finish the branch on making PMP's Surface_mesh compatible with CGAL's algorithm now.

**Pull request closed without merging**
