### PR TITLE
Add low level functions for adding a vertex/edge/face

### PR DESCRIPTION
**Pull request by afabri**
# Description

This PR enables to build a `SurfaceMesh` with low level functions by adding a vertex, edge, or face without an initial point or incident vertices.

I make the section with private functions `new_vertex()` etc  public.

# Motivation

These functions are needed in order to use CGAL functions that add entities for example when calling a [hole filling function](https://github.com/CGAL/cgal/blob/20bf436b50412a81394ba7085f932c83c2213b33/Polygon_mesh_processing/examples/Polygon_mesh_processing/hole_filling_example_PMP.cpp).

# Benefits
This PR completes the low level functions. My guess why they are not provided  is, that you want to avoid that one can produce a mesh that is not valid, but on the other hand as soon as I use one of the `set..()` low level functions the  mesh may be no longer valid. 
Btw, I am wondering if the function `adjust_outgoing_halfedge(..)` must not also be made public.

# Drawbacks

I can't see one.  

# Applicable Issues

Let me know if you want me to file an issue.

### CODE REVIEW

**Comment by dsieger** [comment]
Hi Andreas,

Could you

- Make this PR against the `develop` branch
- Run clang-format

More importantly, the PR currently introduces a bit of code duplication that I would like to avoid:

- The function `SurfaceMesh::new_edge()` is more or less completely duplicated
- The `add_*` functions just wrap the already existing private functions. I think it would be more clean to simply make the `new_*` functions public instead of creating public wrapper functions.

Thanks,
Daniel

**Comment by afabri** [comment]
Hi Daniel,
I added the `add_*()` functions as then they are overloads (that is they have the same name as their already existing counterparts.  Also the `new_*()` functions state that they allocate, what the other `add_*()` functions do not state.  So I removed the "alllocate".   

And I didn't remove the `new_*()` functions, as I didn't want to break backward compatibility, as they have a `private:` doxygen documentation. 

Is the place where I put them ok?

**Comment by dsieger** [comment]
> Hi Daniel,
> I added the `add_*()` functions as then they are overloads (that is they have the same name as their already existing counterparts.

I would argue that overloaded functions add more confusion than separate functions. @mbotsch Any opinions on this?

> Also the `new_*()` functions state that they allocate, what the other `add_*()` functions do not state. So I removed the "alllocate".

I'm not sure I understand what you mean here.

> And I didn't remove the `new_*()` functions, as I didn't want to break backward compatibility, as they have a `private:` doxygen documentation.

Oh we don't care about `private` source level compatibility. It's already hard enough to prevent certain developers from constantly breaking the public API :-)

**Comment by afabri** [comment]
So maybe just tell me in which section of the documentation you want the functions to be listed.

**Pull request merged**
